# NumPy Library

#NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


#1)ndarray.shape =>
This is a tuple of integers indicating the size of the array in each dimension. For a
matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number
of axes, ndim.
- in below output we can see that there are 10 series and one dimension or one row of an array


In [ ]:
print(arr1.shape)

(10,)


# 2) ndarray.ndim =>
the number of axes (dimensions) of the array.

In [ ]:
print(arr1.ndim)

1


#3)dtype =>
it returns the data type of an element of an array.

In [ ]:
print(arr1.dtype)

int64


#4)ndarray.itemsize =>
the size in bytes of each element of the array.

In [ ]:
print(arr1.itemsize)

8


#5)ndarray.size =>
the total number of elements of the array. This is equal to the product of the elements of shape

In [ ]:
print(arr1.size)

10


#6)type =>
it returns the data type


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


# Array Creation
7)Arrange =>
To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range,
but returns an array.

In [ ]:
constant_num = np.arange(10,30,5)
print(constant_num)
float_num = np.arange(0,2,0.3)
print(float_num)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


#8)linespace =>
used to generate the numbers within the given range with equal gap.

In [ ]:
from numpy import pi
print(np.linspace(0,2,9)) # 9 numbers from 0 to 2 with equal gap

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


# 9)reshape =>
used to reshape the array as given below

In [ ]:
a = np.arange(12).reshape(4,3)
print(a)
print("\n")
print(a.reshape(3,4))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#10)random =>
 Declaring the array with random integers


In [ ]:
arr2 = np.random.randint(1,100,(5,5))
print(arr2)

[[64 88 76 30 60]
 [ 8 21 41 19 18]
 [89 44 76 85 57]
 [25 31 69  9 45]
 [84 37 91 16 37]]


#11)Min =>
it returns the Minmum(smallest) element of an array

In [ ]:
print(arr2.min())
print(arr2.min(axis = 0)) #min of each column
print(arr2.min(axis = 1)) #min of each row

8
[ 8 21 41  9 18]
[30  8 44  9 16]


#12)Max =>
it returns the Maximum(largest) element from an array

In [ ]:
print(arr2.max())
print(arr2.max(axis = 0)) #max of each column
print(arr2.max(axis = 1)) #max of each row

91
[89 88 91 85 60]
[88 41 89 69 91]


#13)sum


In [ ]:
print(arr2.sum(axis = 0)) #sum of each column
print(arr2.sum()) # sum of all the elements of an array
print(arr2.sum(axis = 1)) #sum of each row

[270 221 353 159 217]
1220
[318 107 351 179 265]


#14)cumsum =>
it returns the cumulative sum

In [ ]:
print(arr2.cumsum(axis=0)) #cumsum of each column
print(arr2.cumsum()) #cumsum of all the elements of an array
print(arr2.cumsum(axis=1)) #cumsum of each row

[[ 64  88  76  30  60]
 [ 72 109 117  49  78]
 [161 153 193 134 135]
 [186 184 262 143 180]
 [270 221 353 159 217]]
[  64  152  228  258  318  326  347  388  407  425  514  558  634  719
  776  801  832  901  910  955 1039 1076 1167 1183 1220]
[[ 64 152 228 258 318]
 [  8  29  70  89 107]
 [ 89 133 209 294 351]
 [ 25  56 125 134 179]
 [ 84 121 212 228 265]]


#15)sqrt =>
it returns the square-root of each element of an array

In [ ]:
print(np.sqrt(arr2))

[[8.         9.38083152 8.71779789 5.47722558 7.74596669]
 [2.82842712 4.58257569 6.40312424 4.35889894 4.24264069]
 [9.43398113 6.63324958 8.71779789 9.21954446 7.54983444]
 [5.         5.56776436 8.30662386 3.         6.70820393]
 [9.16515139 6.08276253 9.53939201 4.         6.08276253]]


#16)Add =>
it gives addition of each element of an array with similar element of another array

In [ ]:
A = [10,20,30,40,50]
B = [1,2,3,4,5]
print("A => ",A)
print("\n")
print("B => ",B)
print("\n")
print("Addition of A and B => ",np.add(A,B))

A =>  [10, 20, 30, 40, 50]


B =>  [1, 2, 3, 4, 5]


Addition of A and B =>  [11 22 33 44 55]


#17)subtract =>
it gives substraction of each element of an array with similar element of an another array

In [ ]:
print("substraction of A and B => ",np.subtract(A,B))

substraction of A and B =>  [ 9 18 27 36 45]


#18)multiply =>
it gives substraction of each element of an array with similar element of an another array

In [ ]:
print("multiplication of A and B => ",np.multiply(A,B))

multiplication of A and B =>  [ 10  40  90 160 250]


#19)divide =>
it gives substraction of each element of an array with similar element of an another array

In [ ]:
print("division of A and B => ",np.divide(A,B))

division of A and B =>  [10. 10. 10. 10. 10.]


#20)mod
it gives mod of each element of an array with its correspondance array

In [ ]:
print("mod of A and B => ",np.mod(A,B))

mod of A and B =>  [0 0 0 0 0]


#21)remainder =>
Performing remainder on two matrices

In [ ]:
print("remainder of A and B => ",np.remainder(A,B))

remainder of A and B =>  [0 0 0 0 0]


#22)power =>
Performing power of two matrices

In [ ]:
print("power of A and B => ",np.power(A,B))

power of A and B =>  [       10       400     27000   2560000 312500000]


#23)mean
Getting mean of all numbers in A

In [ ]:
print("mean of A => ",np.mean(A))

mean of A =>  30.0


#24)var =>
Getting variance of all number in 'A'

In [ ]:
print("variance of A => ",np.var(A))

variance of A =>  200.0


#25)average =>
it gives us Average of all elements

In [ ]:
print("Average of A => ",np.average(A))

Average of A =>  30.0


#26)transpose =>
it gives transpose of Array

In [ ]:
arr3 = np.random.randint(1,100,(5,5))
print(arr3)
print("\n")
print("transpose of arr3 ")
print(np.transpose(arr3))

[[13 30 57 75 61]
 [74 38 55  7 93]
 [86 18 12 91 93]
 [69 75 19 29 48]
 [ 5 59 85 15 44]]


transpose of arr3 
[[13 74 86 69  5]
 [30 38 18 75 59]
 [57 55 12 19 85]
 [75  7 91 29 15]
 [61 93 93 48 44]]


#27)all =>
it returns the specific rows or columns or entire Array

In [ ]:
print(np.all(arr3 , axis = 0))
print("\n")
print(np.all(arr3 , axis = 1))
print("\n")
print(np.all(arr3 , axis = 0 ,keepdims=True ))
print("\n")
print(np.all(arr3 , axis = 1 , keepdims=True))
print("\n")

[ True  True  True  True  True]


[ True  True  True  True  True]


[[ True  True  True  True  True]]


[[ True]
 [ True]
 [ True]
 [ True]
 [ True]]




#28)argmax =>
The argmax function returns the indices of the maximum values along an axis.

In [ ]:
print(np.argmax(A))
print("\n")

print(np.argmax(arr3))
print("\n")
print(np.argmax(arr3,axis=0))
print("\n")
print(np.argmax(arr3,axis=1))
print("\n")

4


9


[2 3 4 2 1]


[3 4 4 1 2]




#30)argmin =>
The argmin function returns the indices of the minimum values along an axis.

In [ ]:
print(np.argmin(A))
print("\n")

print(np.argmin(arr3))
print("\n")
print(np.argmin(arr3,axis=0))
print("\n")
print(np.argmin(arr3,axis=1))
print("\n")

0


20


[4 2 2 1 4]


[0 3 2 2 0]




#31)argsort =>
The argsort function returns the indices that would sort an array.

In [ ]:
print(np.argsort(A))
print("\n")

print(np.argsort(arr3))
print("\n")
print(np.argsort(arr3,axis=0))
print("\n")
print(np.argsort(arr3,axis=1))
print("\n")

[0 1 2 3 4]


[[0 1 2 4 3]
 [3 1 2 0 4]
 [2 1 0 3 4]
 [2 3 4 0 1]
 [0 3 4 1 2]]


[[4 2 2 1 4]
 [0 0 3 4 3]
 [3 1 1 3 0]
 [1 4 0 0 1]
 [2 3 4 2 2]]


[[0 1 2 4 3]
 [3 1 2 0 4]
 [2 1 0 3 4]
 [2 3 4 0 1]
 [0 3 4 1 2]]




#32)bincount =>
bincount is a function in the numpy library that counts the number of occurrences of each value in an array of non-negative integers.

In [ ]:
arr_count = np.array([0, 1, 1, 2, 2, 2, 3 , 4 ,5 , 6 , 6])
count = np.bincount(arr_count)
print(count)

[1 2 3 1 1 1 2]


#33)clip =>
clip is a function in the numpy library that limits the values in an array.

In [ ]:
clipped_arr = np.clip(arr_count, 2, 4)
print(clipped_arr)

[2 2 2 2 2 2 3 4 4 4 4]


#34)conj =>
conj is a function in the numpy library that returns the complex conjugate of each element in the array.

In [ ]:
arr_conj = np.array([1+2j, 3-4j, 5+6j])
conjugate_arr = np.conj(arr_conj)
print(conjugate_arr)

[1.-2.j 3.+4.j 5.-6.j]


#35)corrcoef =>
corrcoef is a function in the numpy library that returns the Pearson product-moment correlation coefficients.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
correlation_matrix = np.corrcoef(x, y)
print(correlation_matrix)

[[1. 1.]
 [1. 1.]]


#36)cov =>
cov is a function in the numpy library that estimates the covariance matrix of given data.

In [ ]:
covariance_matrix = np.cov(x, y)
print(covariance_matrix)

[[1. 1.]
 [1. 1.]]


#37)cross =>
cross is a function in the numpy library that returns the cross product of two vectors

In [ ]:
cross_product = np.cross(x, y)
print(cross_product)

[-3  6 -3]


#38)cumprod =>
cumprod is a function in the numpy library that returns the cumulative product of elements along a given axis.

In [ ]:
arr_cp= np.array([1, 2, 3, 4])
cumulative_product = np.cumprod(arr_cp)
print(cumulative_product)

[ 1  2  6 24]


#39)diff =>
diff is a function in the numpy library that calculates the n-th discrete difference along the given axis.

In [ ]:
arr = np.array([1, 2, 4, 7, 0])
difference = np.diff(arr)
print(difference)

[ 1  2  3 -7]


#40)dot =>
dot is a function in the numpy library that returns the dot product of two arrays. For 2-D arrays, it is equivalent to matrix multiplication.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(dot_product)

32


#41)floor =>
floor is a function in the numpy and math libraries that returns the largest integer less than or equal to a given number.

In [ ]:
import math
print(np.floor(4.7))  # Output: 4.0
print(math.floor(4.7))  # Output: 4
print(np.floor(a))

4.0
4
[1. 2. 3.]


#42)inner =>
inner is a function in the numpy library that returns the inner product of two arrays.

In [ ]:
inner_product = np.inner(a, b)
print(inner_product)

32


#43)invert =>
invert is a function in the numpy library that computes the bit-wise inversion, or bit-wise NOT, of an array.

In [ ]:
arr = np.array([0, 1, 2, 3], dtype=np.uint8)
inverted_arr = np.invert(arr)
print(inverted_arr)

[255 254 253 252]


#44)lexsort =>
lexsort is a function in the numpy library that performs an indirect sort using a sequence of keys.

In [ ]:
names = ('John', 'Paul', 'George', 'Ringo')
heights = [180, 175, 173, 170]
order = np.lexsort((heights, names))
print(order)

[2 0 1 3]


#45)maximum =>
The numpy.maximum function compares two arrays element-wise and returns a new array containing the maximum values.

In [ ]:
maximum_values = np.maximum(a, b)
print(maximum_values)

[4 5 6]


#46)median =>
median is a function in the numpy library that computes the median along a specified axis.

In [ ]:
arr_median = np.array([1, 2, 3, 4, 5])
median_value = np.median(arr_median)
print(median_value)

3.0


#47)mininum =>
minimum is a function in the numpy library that returns the element-wise minimum of array elements.

In [ ]:
minimum_values = np.minimum(a, b)
print(minimum_values)

[1 2 3]


#48)nonzero =>
nonzero is a function in the numpy library that returns the indices of the elements that are non-zero

In [ ]:
arr_nz = np.array([0, 1, 0, 2, 0, 3])
nonzero_indices = np.nonzero(arr_nz)
print(nonzero_indices)

(array([1, 3, 5]),)


#49)outer =>
uter is a function in the numpy library that computes the outer product of two vectors.

In [ ]:
a_op = np.array([1, 2, 3])
b_op= np.array([4, 5, 6])
outer_product = np.outer(a_op, b_op)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


#50)prod =>
prod is a function in the numpy library that returns the product of array elements over a given axis.

In [ ]:
arr_p = np.array([1, 2, 3, 4])
product = np.prod(arr_p)
print(product)

24


#51)round =>
round is a built-in function in Python that returns the rounded value of a number.

-number: The number to be rounded.

-ndigits: (Optional) The number of decimal places to round to. Defaults to 0.

In [ ]:
num = 4.56789
rounded_num = round(num, 2)
print(rounded_num)

4.57


#52)sort =>
sort is a method in the numpy library that returns a sorted copy of an array.

In [ ]:
arr_sA = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr_sA)
print(sorted_arr)
print("\n")


[1 2 3 4 5]




#53)std =>
std is a function in the numpy library that computes the standard deviation along a specified axis.

In [ ]:
arr_SD = np.array([1, 2, 3, 4, 5])
std_dev = np.std(arr_SD)
print(std_dev)

1.4142135623730951


#54)trace =>
trace is a function in the numpy library that returns the sum of the diagonal elements of an array.

In [ ]:
arr_t = np.array([[1, 2 , 3 , 4], [5, 6 , 7 ,8]])
trace_value = np.trace(arr_t)
print(trace_value)

7


#55)transpose =>
transpose is a method in the numpy library that reverses or permutes the axes of an array.

In [ ]:
transposed_arr = np.transpose(arr_t)
print(transposed_arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


#56)vdot =>
vdot is a function in the numpy library that returns the dot product of two vectors. It treats the input as flat vectors

In [ ]:
a_vdot = np.array([1+2j, 3+4j])
b_vdot = np.array([5+6j, 7+8j])
dot_product = np.vdot(a_vdot, b_vdot)
print(dot_product)

(70-8j)


#57)where =>
where is a function in the numpy library that returns the indices of elements in an input array that satisfy a condition, or it can be used to select elements from two arrays based on a condition.


In [ ]:
arr_where = np.array([0, 1, 2, 3, 4, 5])
indices = np.where(arr_where > 2)
print(indices)

(array([3, 4, 5]),)


#58)Indexing, Slicing and Iterating =>
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [ ]:
print("arr_where[2] => ",arr_where[2])
print("arr_where[2:5] => ",arr_where[2:5])
print("arr_where[:6:2] => ",arr_where[:6:2])
print("arr_where[::-1] => ",arr_where[::-1])
print("arr_where[-2] => ",arr_where[-2])
print("arr_where[-2:-5] => ",arr_where[-2:-5])
print("arr_where[-5:-2] => ",arr_where[-5:-2])
print("arr_where[:-6:-2] => ",arr_where[:-6:-2])
print("Iteration => ")
for i in arr_where:
  print(i)

print("3D arr3 matrix => ")
print(arr3)
print("arr3[2,3] => ",arr3[2,3])
print("arr3[0:5, 1] => ",arr3[0:5, 1]) # each row in the second column of b
print("arr3[:, 1] => ",arr3[:, 1])
print("arr3[1:3, :] => ",arr3[1:3, :]) # each column in the second and third row of b

arr_where[2] =>  2
arr_where[2:5] =>  [2 3 4]
arr_where[:6:2] =>  [0 2 4]
arr_where[::-1] =>  [5 4 3 2 1 0]
arr_where[-2] =>  4
arr_where[-2:-5] =>  []
arr_where[-5:-2] =>  [1 2 3]
arr_where[:-6:-2] =>  [5 3 1]
Iteration => 
0
1
2
3
4
5
3D arr3 matrix => 
[[13 30 57 75 61]
 [74 38 55  7 93]
 [86 18 12 91 93]
 [69 75 19 29 48]
 [ 5 59 85 15 44]]
arr3[2,3] =>  91
arr3[0:5, 1] =>  [30 38 18 75 59]
arr3[:, 1] =>  [30 38 18 75 59]
arr3[1:3, :] =>  [[74 38 55  7 93]
 [86 18 12 91 93]]
				


#59)copy =>
copy is a method in the numpy library that returns a copy of an array

In [ ]:
original_array = np.array([1, 2, 3])
copied_array = original_array.copy()
print("Copy:", copied_array)

Copy: [1 2 3]


#60)empty =>
empty is a function in the numpy library that returns a new array of a given shape and type, without initializing entries

In [ ]:
empty_array = np.empty((2, 3))
print("Empty:", empty_array)

Empty: [[4.74188299e-310 0.00000000e+000 2.05833592e-312]
 [6.79038654e-313 2.14321575e-312 2.27053550e-312]]


#61)empty_like =>
empty_like is a function in the numpy library that returns a new array with the same shape and type as a given array, without initializing entries.

In [ ]:
array_like = np.array([[1, 2, 3], [4, 5, 6]])
empty_like_array = np.empty_like(array_like)
print(empty_like_array)

[[95976778955476              0              0]
 [             0              0              0]]


#62)eye =>
eye is a function in the numpy library that returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
identity_matrix = np.eye(3)
print("Eye (Identity matrix):", identity_matrix)

Eye (Identity matrix): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#63)identity =>
identity is a function in the numpy library that returns a square identity matrix.

In [ ]:
identity_array = np.identity(4)
print("Identity:", identity_array)

Identity: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#64)zeros =>
zeros is a function in the numpy library that returns a new array of a given shape and type, filled with zeros.

In [ ]:
zeros_array = np.zeros((2, 3))
print("Zeros:", zeros_array)

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]


#65)ones =>
ones is a function in the numpy library that returns a new array of a given shape and type, filled with ones.

In [ ]:
ones_array = np.ones((2, 3))
print("Ones:", ones_array)

Ones: [[1. 1. 1.]
 [1. 1. 1.]]


#66)array_split =>
array_split is a function in the numpy library that splits an array into multiple sub-arrays.**bold text**

In [ ]:
split_array = np.array_split(np.arange(10), 3)
print("Array split:", split_array)

Array split: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


#67)column_stack =>
column_stack is a function in the numpy library that stacks 1-D arrays as columns into a 2-D **array**

In [ ]:
a_c_stack = np.array([1, 2, 3])
b_c_stack = np.array([4, 5, 6])
stacked_array = np.column_stack((a_c_stack, b_c_stack))
print("Column stack:", stacked_array)

Column stack: [[1 4]
 [2 5]
 [3 6]]


#68)concatenate =>
concatenate is a function in the numpy library that joins a sequence of arrays along an existing axis

In [ ]:
concat_array = np.concatenate((a_c_stack, b_c_stack))
print("Concatenate:", concat_array)

Concatenate: [1 2 3 4 5 6]


#69)diagonal =>
diagonal is a function in the numpy library that returns specified diagonals

In [ ]:
diag_matrix = np.diag([1, 2, 3])
print("Diagonal:", np.diagonal(diag_matrix))

Diagonal: [1 2 3]


#70)dsplit =>
dsplit is a function in the numpy library that splits an array into multiple sub-arrays along the 3rd axis (depth)

In [ ]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
dsplit_array = np.dsplit(array_3d, 3)
print("Dsplit:", dsplit_array)

Dsplit: [array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])]


#71)dstack =>
dstack is a function in the numpy library that stacks arrays in sequence depth-wise (along the third axis

In [ ]:
dstacked_array = np.dstack((a_c_stack, b_c_stack))
print("Dstack:", dstacked_array)

Dstack: [[[1 4]
  [2 5]
  [3 6]]]


#72)hsplit =>
hsplit is a function in the numpy library that splits an array into multiple sub-arrays horizontally (column-wise)

In [ ]:
hsplit_array = np.hsplit(np.array([[1, 2, 3, 4], [5, 6, 7, 8]]), 2)
print("Hsplit:", hsplit_array)

Hsplit: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


#73)hstack =>
hstack is a function in the numpy library that stacks arrays in sequence horizontally (column-wise

In [ ]:
hstacked_array = np.hstack((a_c_stack[:, np.newaxis], b_c_stack[:, np.newaxis]))
print("Hstack:", hstacked_array)

Hstack: [[1 4]
 [2 5]
 [3 6]]


#74)ravel =>
ravel is a function in the numpy library that returns a contiguous flattened array.

In [ ]:
ravelled_array = np.ravel(np.array([[1, 2, 3], [4, 5, 6]]))
print("Ravel:", ravelled_array)

Ravel: [1 2 3 4 5 6]


#75)repeat =>
repeat is a function in the numpy library that repeats elements of an array

In [ ]:
repeated_array = np.repeat(a_c_stack, 2)
print("Repeat:", repeated_array)

Repeat: [1 1 2 2 3 3]


#76)squeeze =>
squeeze is a function in the numpy library that removes single-dimensional entries from the shape of an array

In [ ]:
squeezed_array = np.array([[[1, 2, 3]]]).squeeze()
print("Squeeze:", squeezed_array)

Squeeze: [1 2 3]


#77)swapaxes =>
swapaxes is a function in the numpy library that interchanges two axes of an array

In [ ]:
swap_axes_array = np.swapaxes(np.array([[1, 2, 3], [4, 5, 6]]), 0, 1)
print("Swapaxes:", swap_axes_array)

Swapaxes: [[1 4]
 [2 5]
 [3 6]]


#78)take =>
take is a function in the numpy library that takes elements from an array along an axis.

In [ ]:
taken_elements = np.take(np.array([10, 11, 12, 13]), [0, 2])
print("Take:", taken_elements)

Take: [10 12]


#79)vsplit =>
vsplit is a function in the numpy library that splits an array into multiple sub-arrays vertically (row-wise

In [ ]:
vsplit_array = np.vsplit(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 3)
print("Vsplit:", vsplit_array)

Vsplit: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


#80)vstack =>
vstack is a function in the numpy library that stacks arrays in sequence vertically (row-wise)

In [ ]:
vstacked_array = np.vstack((a_c_stack, b_c_stack))
print("Vstack:", vstacked_array)


Vstack: [[1 2 3]
 [4 5 6]]


#81)newaxis =>
newaxis is used in the numpy library to increase the dimensions of an array by one more dimension, when used once

In [ ]:
newaxis_array = a_c_stack[:, np.newaxis]
print("Newaxis:", newaxis_array)

Newaxis: [[1]
 [2]
 [3]]


#82)astype =>
astype is a method of ndarray objects in the numpy library that returns a copy of the array, cast to a specified type.

In [ ]:
float_array = a_c_stack.astype(float)
print("Astype (to float):", float_array)

Astype (to float): [1. 2. 3.]


#83)atleast_1d =>
atleast_1d is a function in the numpy library that converts inputs to arrays with at least one dimension.

In [ ]:
atleast_1d_array = np.atleast_1d(5)
print("Atleast 1d:", atleast_1d_array)

Atleast 1d: [5]


#84)atleast_2d =>
atleast_2d is a function in the numpy library that converts inputs to arrays with at least two dimensions.

In [ ]:
atleast_2d_array = np.atleast_2d(a_c_stack)
print("Atleast 2d:", atleast_2d_array)

Atleast 2d: [[1 2 3]]


#85)atleast_3d =>
atleast_3d is a function in the numpy library that converts inputs to arrays with at least three dimensions.



In [ ]:
atleast_3d_array = np.atleast_3d(a_c_stack)
print("Atleast 3d:", atleast_3d_array)

Atleast 3d: [[[1]
  [2]
  [3]]]


#86)mat =>
mat is a function in the numpy library that interprets the input as a matrix. This function is largely deprecated in favor of ndarray

In [ ]:
mat_array = np.mat('1 2; 3 4')
print("Mat:", mat_array)

Mat: [[1 2]
 [3 4]]
