#create the dummy Datasets

#Model Building

In [ ]:
import numpy as np
import pandas as pd

#for classification
# 2D array X with 100 rows and 5 columns.Each element in X is a random
# float number between 0 and 1, generated from a uniform distribution.
X, y_classification = np.random.rand(100, 5), np.random.randint(0, 2, size=100)

#for regression
#This line generates a 1D array y_classification containing 100 integers.
#Each integer is randomly chosen from the set {0, 1}.

y_regression = np.random.rand(100)



#(1)train_test_split () =>
Use the function to split your data into training and testing sets

In [ ]:
from sklearn.model_selection import train_test_split

#Split the dataset into training and testing sets
#The test_size=0.2 => parameter indicates that 20% of the data will be reserved for testing, while the remaining 80% will be used for training
#random_state=42  => ensures that the data is split in the same way every time the code is run, allowing for reproducible results.

X_train, X_test, y_train_classification, y_test_classification = train_test_split(X, y_classification, test_size=0.2, random_state=42)
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_regression, test_size=0.2, random_state=42)


#(2) Linear Regression () =>
-The LinearRegression() function in Python helps create a model that finds the best-fit straight line through your data.

-In short, it helps to predict a future outcome based on past data by learning a simple line equation.








In [ ]:
from sklearn.linear_model import LinearRegression

#LinearRegression class is being created and stored in the variable lin_reg.
lin_reg = LinearRegression()

#X_train_reg =>  represents the independent variable(s) of the training dataset.
#y_train_reg =>  represents the dependent variable in the training dataset.
#The fit() =>  method trains the linear regression model on the training data.

lin_reg.fit(X_train_reg, y_train_reg)

#retrieves the coefficients of the linear regression model using the coef_ attribute.
print("Linear Regression Coefficients:", lin_reg.coef_)

Linear Regression Coefficients: [ 0.0313198   0.03755143 -0.0778522  -0.11894204  0.18818602]


#(3)LogisticRegression () =>
The LogisticRegression() function in Python is used to create a model that predicts the probability of a binary outcome (like yes/no or 0/1) based on input data.

In [ ]:
from sklearn.linear_model import LogisticRegression

# creates an instance of the LogisticRegression class and stores it in the variable log_reg.
log_reg = LogisticRegression()

#X_train represents => (independent variables) of the training dataset.
#y_train_classification represents => (dependent variable),

log_reg.fit(X_train, y_train_classification)
print("Logistic Regression Coefficients:", log_reg.coef_)

Logistic Regression Coefficients: [[-0.35257797 -0.26603844 -0.26947525  0.09471063  0.48061701]]


#(4)DecisionTreeClassifier () =>
-creates a model that makes decisions to classify data into categories.

-It uses a tree-like structure where:

-Nodes represent decisions based on input features.
Branches lead to  final classifications.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train_classification)

#This line checks how good the decision tree model is at making predictions and shows the result.
#X_test: This is the new data (features) that the model hasn't seen before.
#y_test_classification: This is the real answers for the new data.

print("Decision Tree Classifier Score:", dt_classifier.score(X_test, y_test_classification))

Decision Tree Classifier Score: 0.35


#(5) DecisionTreeRegressor () =>
-DecisionTreeRegressor() is a tool that predicts numbers, like house prices, using a tree-like structure that makes decisions based on input features

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt_regressor = DecisionTreeRegressor()

#X_test_reg: This is the new data (features) that the model hasn't seen before.
#y_test_reg: This is the real answers for the new data.
dt_regressor.fit(X_train_reg, y_train_reg)
print("Decision Tree Regressor Score:", dt_regressor.score(X_test_reg, y_test_reg))


Decision Tree Regressor Score: 0.43063684750307774


#(6)RandomForestClassifier () =>
-machine learning model that combines multiple decision trees to improve classification accuracy.

- It works by creating a "forest" of decision trees, each trained on different random samples of the data, and then takes a majority vote to make predictions.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train_classification)

#X_test: This is the new data (features) that the model hasn't seen before.
#y_test_classification: This is the real answers for the new data.
print("Random Forest Classifier Score:", rf_classifier.score(X_test, y_test_classification))


Random Forest Classifier Score: 0.5


#(7)RandomForestRegressor () =>
-machine learning model used to predict continuous values by combining the predictions of multiple decision trees.

-It creates a "forest" of trees, each trained on random samples of the data, and averages their predictions to improve accuracy and reduce

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor()
rf_regressor.fit(X_train_reg, y_train_reg)

#X_test_reg: This is the new data (features) that the model hasn't seen before.
#y_test_reg: This is the real answers for the new data.
print("Random Forest Regressor Score:", rf_regressor.score(X_test_reg, y_test_reg))


Random Forest Regressor Score: 0.3031393436329737


#(8) GradientBoostingClassifier () =>
-machine learning model that combines many simple decision trees to make predictions about categories (like spam or not spam).

-It builds these trees one after the other, and each new tree tries to fix the mistakes made by the previous ones, which helps improve the overall accuracy of the model

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gb_classifier = GradientBoostingClassifier()
gb_classifier.fit(X_train, y_train_classification)

#X_test: This is the new data (features) that the model hasn't seen before.
#y_test_classification: This is the real answers for the new data.
print("Gradient Boosting Classifier Score:", gb_classifier.score(X_test, y_test_classification))


Gradient Boosting Classifier Score: 0.65


#(9) GradientBoostingRegressor() =>
-machine learning model used for predicting continuous values, such as prices or temperatures.

- It builds multiple simple decision trees in sequence, where each new tree aims to correct the errors made by the previous ones.

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb_classifier = GradientBoostingClassifier()
gb_classifier.fit(X_train, y_train_classification)

#X_test: This is the new data (features) that the model hasn't seen before.
#y_test_classification: This is the real answers for the new data.
print("Gradient Boosting Classifier Score:", gb_classifier.score(X_test, y_test_classification))


Gradient Boosting Classifier Score: 0.65


#(10)GradientBoostingRegressor() =>
-machine learning model used for predicting continuous values, such as prices or temperatures.

- It builds multiple simple decision trees in sequence, where each new tree aims to correct the errors made by the previous ones.

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb_classifier = GradientBoostingClassifier()
gb_classifier.fit(X_train, y_train_classification)

#X_test: This is the new data (features) that the model hasn't seen before.
#y_test_classification: This is the real answers for the new data.
print("Gradient Boosting Classifier Score:", gb_classifier.score(X_test, y_test_classification))


NameError: name 'X_train' is not defined

#(11)Support Vector Classifier() =>
-machine learning model used for classification tasks.

-It works by finding the best boundary (or hyperplane) that separates different categories in the data.

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train_classification)

#X_test: This is the new data (features) that the model hasn't seen before.
#y_test_classification: This is the real answers for the new data.
print("Support Vector Classifier Score:", svc.score(X_test, y_test_classification))


Support Vector Classifier Score: 0.6


#(12) Support Vector Regression() =>
-machine learning model used for predicting continuous values.

- It extends the concept of Support Vector Classifier (SVC) to regression tasks by finding a function that approximates the data while allowing for some errors.

In [ ]:
from sklearn.svm import SVR
# Support Vector Regressor
svr = SVR()
svr.fit(X_train_reg, y_train_reg)

#X_test_reg: This is the new data (features) that the model hasn't seen before.
#y_test_reg: This is the real answers for the new data.
print("Support Vector Regressor Score:", svr.score(X_test_reg, y_test_reg))


Support Vector Regressor Score: 0.0370706226883748


#(13)K-Neighbors Classifier () =>
-machine learning model that classifies data points based on the majority class among their closest neighbors in the feature space.

-It looks at a specified number of nearby points (k) to decide which category a new data point belongs to, making it simple and effective for many classification tasks

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Create an instance of the KNeighborsClassifier
kn_classifier = KNeighborsClassifier()

# Fit the model using the training data
kn_classifier.fit(X_train, y_train_classification)

# X_test: This is the new data (features) that the model hasn't seen before.
# y_test_classification: This is the real answers for the new data.
print("K-Nearest Neighbors Classifier Score:", kn_classifier.score(X_test, y_test_classification))


K-Nearest Neighbors Classifier Score: 0.55


#(14) KNeighborsRegressor () =>
-machine learning model used for predicting continuous values based on the average of the values from the nearest neighbors in the dataset.

-It looks at a specified number of nearby data points (k) and predicts the target value by averaging their outputs, making it a straightforward and intuitive approach for regression tasks.

In [ ]:
from sklearn.neighbors import KNeighborsRegressor  # Import KNeighborsRegressor

# Create an instance of the KNeighborsRegressor
kn_regressor = KNeighborsRegressor()

# Fit the model using the training data
kn_regressor.fit(X_train_reg, y_train_reg)

# Evaluate the model and print the R^2 score
print("K-Nearest Neighbors Regressor Score:", kn_regressor.score(X_test_reg, y_test_reg))


K-Nearest Neighbors Regressor Score: -0.19783655315235182


In [ ]:
# Generate a dummy dataset
X, y = np.random.rand(100, 5), np.random.randint(0, 2, size=100)  # Features and binary target variable

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


#(15)GaussianNB () =>
-classification model that makes predictions based on the assumption that the features (inputs) are normally distributed (like a bell curve).

-It calculates the probabilities for each class and chooses the class with the highest probability, making it simple and effective for many types of data

In [ ]:
from sklearn.naive_bayes import GaussianNB
# Gaussian Naive Bayes Classifier
gnb = GaussianNB()
gnb.fit(X_train, y_train)

#X_test is the data we use to test our model, and y_test is the correct answers for that data.
#By comparing the model's predictions with y_test, we can see how well the model is doing
print("GaussianNB Score:", gnb.score(X_test, y_test))

GaussianNB Score: 0.55


#(16)BernoulliNB () =>
-machine learning tool used for classifying data with binary features, like yes/no or true/false.

-It calculates the probability of different classes (like spam or not spam) based on the presence or absence of specific features and is often used in tasks like email filtering

In [ ]:
from sklearn.naive_bayes import BernoulliNB
# Bernoulli Naive Bayes Classifier
bnb = BernoulliNB()
bnb.fit(X_train, y_train)

#X_test is the data we use to test our model, and y_test is the correct answers for that data.
#By comparing the model's predictions with y_test, we can see how well the model is doing
print("BernoulliNB Score:", bnb.score(X_test, y_test))


BernoulliNB Score: 0.35


#(17)MultinomialNB () =>
-The MultinomialNB() function is a machine learning classifier used for text classification tasks where the features are counts or frequencies, such as the number of times a word appears in a document.

In [ ]:
from sklearn.naive_bayes import MultinomialNB
# Multinomial Naive Bayes Classifier
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

#X_test is the data we use to test our model, and y_test is the correct answers for that data.
#By comparing the model's predictions with y_test, we can see how well the model is doing
print("MultinomialNB Score:", mnb.score(X_test, y_test))


MultinomialNB Score: 0.45


#(18)SGDClassifier () =>
-The SGDClassifier() function is a machine learning tool that uses Stochastic Gradient Descent (SGD) for training models.

-It’s particularly useful for large datasets because it updates the model incrementally, making it efficient in terms of memory and computation.

In [ ]:
from sklearn.linear_model import SGDClassifier
# Stochastic Gradient Descent Classifier
sgd_classifier = SGDClassifier()
sgd_classifier.fit(X_train, y_train)

#X_test is the data we use to test our model, and y_test is the correct answers for that data.
#By comparing the model's predictions with y_test, we can see how well the model is doing
print("SGDClassifier Score:", sgd_classifier.score(X_test, y_test))


SGDClassifier Score: 0.45


# Model Evaluation

In [ ]:
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV, train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import (
    classification_report, confusion_matrix, precision_score, recall_score,
    f1_score, accuracy_score, roc_curve, roc_auc_score, mean_squared_error,
    r2_score, mean_absolute_error, explained_variance_score, log_loss,
    brier_score_loss, make_scorer
)

# Classification dataset
X, y_classification = np.random.rand(100, 5), np.random.randint(0, 2, size=100)
# Regression dataset
y_regression = np.random.rand(100)

# Split the data into train and test sets
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X, y_classification, test_size=0.2, random_state=42)
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_regression, test_size=0.2, random_state=42)

# Logistic Regression model for classification
clf = LogisticRegression()
clf.fit(X_train_clf, y_train_clf)
y_pred_clf = clf.predict(X_test_clf)

# Linear Regression model for regression
reg = LinearRegression()
reg.fit(X_train_reg, y_train_reg)
y_pred_reg = reg.predict(X_test_reg)


#(19)cross_val_score () =>
-used to evaluate the performance of a machine learning model by splitting the data into multiple parts (or folds).

-It trains the model on some of the folds and tests it on the remaining fold, repeating this process several times. This helps to get a more  accuracy by averaging the scores from each fold.

In [ ]:
from sklearn.metrics import classification_report

#clf =>  This is your classification model that you want to evaluat.
#X_train_clf => This is the data set of your training data.
#y_train_clf: This is the target variable (labels) corresponding to the training data.
#cv=5: This specifies that the training data should be split into 5 equal parts (folds) for cross-validation.

cv_scores_clf = cross_val_score(clf, X_train_clf, y_train_clf, cv=5)
print("Cross-validation scores (classification):", cv_scores_clf)  #This line prints the array of cross-validation scores

# Fit and predict for classification
clf.fit(X_train_clf, y_train_clf)

#This line uses the trained model to make predictions on the test feature set (X_test_clf).
#The predicted labels are stored in the variable y_pred_class.
y_pred_class = clf.predict(X_test_clf)

Cross-validation scores (classification): [0.5    0.625  0.4375 0.4375 0.5625]


#(20)GridSearchCV ()=>
-GridSearchCV() is a tool in machine learning that helps you find the best combination of parameters (settings) for your model.

-It does this by testing all possible combinations of given parameters and checking which one performs the best using cross-validation, ensuring your model is accurate and reliable.

In [ ]:
from sklearn.metrics import confusion_matrix
grid_clf.fit(X_train_clf, y_train_clf)
print("Best params (GridSearchCV):", grid_clf.best_params_)

NameError: name 'grid_clf' is not defined

#(21)classification_report () =>
-provides a summary of key metrics (precision, recall, F1-score, and support) to evaluate the performance of a classification model.

-It helps you understand how well your model performed for each class in a classification task.


In [ ]:
print("\nClassification Report:")

#classification_report => This function, from the sklearn.metrics module, creates a report showing how well a classification model has performed.
#y_test_clf => This is the list or array of true labels (the actual categories or classes) from the test dataset.
#y_pred_clf => This is the list or array of predicted labels (the categories or classes that the model predicted for the test dataset).

print(classification_report(y_test_clf, y_pred_clf))


Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.38      0.50        13
           1       0.38      0.71      0.50         7

    accuracy                           0.50        20
   macro avg       0.55      0.55      0.50        20
weighted avg       0.60      0.50      0.50        20



#(22) confusion_matrix () =>
-The confusion_matrix is a tool used to evaluate the performance of a classification model. It shows how many predictions were correctly or incorrectly classified by the model, breaking it down into four categories :

-TP TN FP FN

In [ ]:
print("\nConfusion Matrix:")

#y_test_clf: This is the list or array of true labels (the actual categories or classes) from the test dataset.
#y_pred_clf: This is the list or array of predicted labels (the categories or classes predicted by the model for the test dataset)

print(confusion_matrix(y_test_clf, y_pred_clf))


Confusion Matrix:
[[6 7]
 [4 3]]


#(23)Precision score() =>
-The precision score is a metric used to evaluate the accuracy of positive predictions in classification.

-checks how many of the positive predictions made by a model were actually correct. It's important when you want to avoid false alarms and make sure positive results are accurate



In [ ]:
#y_test_clf => This is the list or array of true labels (the actual classes) from the test dataset.
#y_pred_class => This is the list or array of predicted labels (the classes predicted by the model) for the test dataset

print("\nPrecision Score:", precision_score(y_test_clf, y_pred_class))


Precision Score: 0.42857142857142855


#(24)Recall Score () =>
 -Measures the model's ability to identify true positives out of all actual positives, useful when minimizing false negatives is critical.

In [ ]:
#y_test_clf => This is the list or array of true labels (the actual categories or classes) from the test dataset.
#y_pred_clf => This is the list or array of predicted labels (the categories or classes predicted by the model for the test dataset)

print("Recall Score:", recall_score(y_test_clf, y_pred_clf))

Recall Score: 0.2222222222222222


#(25) F1 Score () =>
-Balances precision and recall, useful when both false positives and false negatives matter.

In [ ]:
#y_test_clf => This is the list or array of true labels (the actual categories or classes) from the test dataset.
#y_pred_clf => This is the list or array of predicted labels (the categories or classes predicted by the model for the test dataset)
print("F1 Score:", f1_score(y_test_clf, y_pred_clf))

F1 Score: 0.26666666666666666


#(26)Accuracy Score () =>
 -Measures the proportion of correct predictions, but can be misleading in imbalanced datasets.

In [ ]:
#y_test_clf => This is the list or array of true labels (the actual categories or classes) from the test dataset.
#y_pred_clf => This is the list or array of predicted labels (the categories or classes predicted by the model for the test dataset)

print("Accuracy Score:", accuracy_score(y_test_clf, y_pred_clf))

Accuracy Score: 0.45


#(27)Accuracy Score () =>
 -Measures the proportion of correct predictions, but can be misleading in imbalanced datasets.

In [ ]:
#y_test_clf: This is the list or array of true labels (the actual categories or classes) from the test dataset.
#y_pred_clf: This is the list or array of predicted labels (the categories or classes predicted by the model for the test dataset).

print("Accuracy Score:", accuracy_score(y_test_clf, y_pred_clf))

Accuracy Score: 0.45


#(28)R² Score () =>
-It's useful for assessing the quality of the model—higher values indicate a better fit to the data.

In [ ]:
#y_test_reg: This is the list or array of true values (the actual outcomes) from the test dataset.
#y_pred_reg: This is the list or array of predicted values (the outcomes predicted by the model) for the test dataset.

print("R^2 Score:", r2_score(y_test_reg, y_pred_reg))

R^2 Score: -0.15161108239164256


#(29)Mean Absolute Error (MAE) =>
 -Measures the average absolute difference between predicted and actual values, less sensitive to outliers than MSE.

In [ ]:
#y_test_reg => This is the list or array of true values (the actual outcomes) from the test dataset.
#y_pred_reg => This is the list or array of predicted values (the outcomes predicted by the model) for the test dataset.

print("Mean Absolute Error (MAE):", mean_absolute_error(y_test_reg, y_pred_reg))


Mean Absolute Error (MAE): 0.22254696210376027


#(30)Explained Variance Score () =>
 -Measures the proportion of variance explained by the model, indicating the model’s performance.

In [ ]:
#y_test_reg => This is the list or array of true values (the actual outcomes) from the test dataset.
#y_pred_reg => This is the list or array of predicted values (the outcomes predicted by the model) for the test dataset.

print("Explained Variance Score:", explained_variance_score(y_test_reg, y_pred_reg))


Explained Variance Score: -0.13179928754049675


#(31)StandardScaler(): =>
-standardizes the features of your dataset. It transforms the data so that it has a mean of 0 and a standard deviation of 1.

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data = [[1, 2], [3, 4], [5, 6]]

#Fit => It calculates the mean and standard deviation for each feature in the data.
#Transform => It standardizes the data by subtracting the mean and dividing by the standard deviation for each feature.

scaled_data = scaler.fit_transform(data)
print("Standard Scaled Data:\n", scaled_data)


Standard Scaled Data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


#(32)MinMaxScaler() =>
-scales the features of your data to a specific range, usually between 0 and 1. This helps ensure that all features have the same importance, which can improve the performance of some machine learning models.

In [ ]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
data = [[1, 2], [3, 4], [5, 6]]
scaled_data = scaler.fit_transform(data)
print("Min-Max Scaled Data:\n", scaled_data)


Min-Max Scaled Data:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


#(33)MaxAbsScaler() =>
 -Scales each feature by its maximum absolute value, preserving sparsity and scaling the data within the range of [-1, 1].

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
data = [[1, 2], [3, 4], [5, 6]]
scaled_data = scaler.fit_transform(data)
print("Min-Max Scaled Data:\n", scaled_data)


Min-Max Scaled Data:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


#(34)RobustScaler() =>
 -Scales features using statistics that are robust to outliers, specifically by removing the median and scaling according to the interquartile range (IQR).

In [ ]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
data = [[1, 2], [3, 4], [5, 6], [100, 200]]
scaled_data = scaler.fit_transform(data)
print("Robust Scaled Data:\n", scaled_data)


Robust Scaled Data:
 [[-0.11428571 -0.05882353]
 [-0.03809524 -0.01960784]
 [ 0.03809524  0.01960784]
 [ 3.65714286  3.82352941]]


#(35)Normalizer() =>
 -Scales individual samples to have a unit norm (length), transforming each sample to lie on the hypersphere of radius 1.



In [ ]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer()
data = [[1, 2], [3, 4], [5, 6]]
normalized_data = normalizer.fit_transform(data)
print("Normalized Data:\n", normalized_data)


Normalized Data:
 [[0.4472136  0.89442719]
 [0.6        0.8       ]
 [0.6401844  0.76822128]]


#(36)Binarizer() =>
 -Converts numerical features into binary values (0 or 1) based on a specified threshold, turning any value above the threshold into 1 and below into 0

In [ ]:
from sklearn.preprocessing import Binarizer

#Binarizer => This is a class in the sklearn library that is used to convert numerical data into binary values (0s and 1s) based on a specified threshold.threshold=3.0:
#This sets the threshold value at 3.0. It means that any value in the data that is greater than or equal to 3.0 will be converted to 1, and any value that is less than 3.0 will be converted to 0.

binarizer = Binarizer(threshold=3.0)
data = [[1, 2], [3, 4], [5, 6]]
binary_data = binarizer.fit_transform(data)
print("Binarized Data:\n", binary_data)


Binarized Data:
 [[0 0]
 [0 1]
 [1 1]]


#(37)PolynomialFeatures() =>
 Generates polynomial and interaction features from the original features, allowing for the inclusion of non-linear relationships in linear models.

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

#the program to create new features based on your original features, using mathematical powers up to 2.
poly = PolynomialFeatures(degree=2)
data = [[1, 2], [3, 4]]
poly_data = poly.fit_transform(data)
print("Polynomial Features:\n", poly_data)


Polynomial Features:
 [[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]]


#(38)OneHotEncoder() =>
 -Converts categorical variables into a format that can be provided to ML algorithms to do a better job in prediction, creating binary columns for each category.

 -it require numerical input, and this encoding helps represent categories without implying any ordinal relationship between them

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
data = [[0], [1], [2]]
encoded_data = encoder.fit_transform(data).toarray()
print("One-Hot Encoded Data:\n", encoded_data)


One-Hot Encoded Data:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#(39)LabelEncoder() =>
 -Converts categorical labels into integer values, providing a way to represent categories numerically for ML algorithms.

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
data = ['cat', 'dog', 'cat', 'bird']
encoded_labels = encoder.fit_transform(data)
print("Label Encoded Data:\n", encoded_labels)


Label Encoded Data:
 [1 2 1 0]


#(40)OrdinalEncoder() =>
 -Encodes categorical features as ordinal integers, maintaining the order of categories, which is useful for ordinal data.

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
data = [['cat'], ['dog'], ['bird']]
encoded_data = encoder.fit_transform(data)
print("Ordinal Encoded Data:\n", encoded_data)


#(41)SimpleImputer() =>
 Fills in missing values in datasets using a specified strategy (mean, median, most frequent, or constant) for imputation.

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
data = [[1, 2], [None, 3], [7, 6]]
imputed_data = imputer.fit_transform(data)
print("Imputed Data:\n", imputed_data)


Imputed Data:
 [[1. 2.]
 [4. 3.]
 [7. 6.]]


#(42)KNNImputer() =>
 Imputes missing values by using the k-nearest neighbors algorithm, filling in missing values based on the mean of the nearest neighbors.

In [ ]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)
data = [[1, 2], [None, 3], [7, 6]]
imputed_data = imputer.fit_transform(data)
print("KNN Imputed Data:\n", imputed_data)


KNN Imputed Data:
 [[1. 2.]
 [4. 3.]
 [7. 6.]]


#(43)PowerTransformer() =>
 Applies a power transformation to make data more Gaussian-like, which can help improve the performance of machine learning algorithms.

In [ ]:
from sklearn.preprocessing import PowerTransformer

transformer = PowerTransformer()
data = [[1, 2], [3, 4], [5, 6]]
transformed_data = transformer.fit_transform(data)
print("Power Transformed Data:\n", transformed_data)


Power Transformed Data:
 [[-1.26755013 -1.25808855]
 [ 0.09064754  0.06966078]
 [ 1.17690259  1.18842777]]


#(44)QuantileTransformer() =>
Transforms features to follow a uniform or normal distribution. This is especially useful for handling outliers.

In [ ]:
from sklearn.preprocessing import QuantileTransformer

transformer = QuantileTransformer(output_distribution='normal')
data = [[1], [2], [3], [4], [5]]
transformed_data = transformer.fit_transform(data)
print("Quantile Transformed Data:\n", transformed_data)


Quantile Transformed Data:
 [[-5.19933758]
 [-0.67448975]
 [ 0.        ]
 [ 0.67448975]
 [ 5.19933758]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_data.py:2785: UserWarning: n_quantiles (1000) is greater than the total number of samples (5). n_quantiles is set to n_samples.
  warnings.warn(


#(45)LabelBinarizer() =>
Binarizes labels in a multi-class setting, encoding them as binary arrays.

In [ ]:
from sklearn.preprocessing import LabelBinarizer

binarizer = LabelBinarizer()
data = ['cat', 'dog', 'cat', 'bird']
binarized_data = binarizer.fit_transform(data)
print("Label Binarized Data:\n", binarized_data)


Label Binarized Data:
 [[0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


#(46)add_dummy_feature() =>
Adds a column of ones to the input data (useful for linear regression to account for the intercept).

In [ ]:
from sklearn.preprocessing import add_dummy_feature

data = [[1], [2], [3]]
dummy_data = add_dummy_feature(data)
print("Data with Dummy Feature:\n", dummy_data)


Data with Dummy Feature:
 [[1. 1.]
 [1. 2.]
 [1. 3.]]
