#Introduction to tensorflow library
-TensorFlow is an open-source machine learning library developed by Google.

-TensorFlow is used to build and train deep learning models as it facilitates the creation of computational graphs and efficient execution on various hardware platforms.

-The article provides an comprehensive overview of tensorflow

#Importing the required libraries

In [ ]:
import tensorflow as tf
import numpy as np

#(1)creating a constant tensor () =>
-The tf.constant() function is used to create a TensorFlow tensor with fixed values.

-It stores data like numbers or arrays in a way that TensorFlow can process for machine learning tasks.

-You can also specify the data type, such as integers or floats.

In [ ]:
#tf.constant([1, 2, 3]) => This creates a TensorFlow tensor (a kind of data structure) containing the values [1, 2, 3].

tensor1 = tf.constant([1, 2, 3])
print(tensor1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


#(2)tf.random() =>
-tf.random.uniform() generates a tensor filled with random numbers from a uniform distribution, where all values between a specified range (e.g., minval and maxval) have an equal chance of being chosen.

- It's useful for initializing variables or creating random data in machine learning models.

In [ ]:
#tf.random.uniform() => This is a TensorFlow function that generates a tensor with random values drawn from a uniform distribution.
                        #In a uniform distribution, all values in a given range are equally likely.
#minval=0 => The smallest possible value that can appear in the tensor is 0.
#maxval=1 => The values generated will be between 0 (inclusive) and 1 (exclusive), meaning they can be as large as 0.9999 but never exactly 1.

random_tensor = tf.random.uniform([3, 3], minval=0, maxval=1)
print(random_tensor)

tf.Tensor(
[[0.11997771 0.03074241 0.41245222]
 [0.3929956  0.09057045 0.14413905]
 [0.371287   0.9743335  0.09112883]], shape=(3, 3), dtype=float32)


#(3)tf.reshape() =>
-This TensorFlow function reshapes a given tensor without changing its data.
- It changes the shape (or structure) of the tensor but keeps the same number of elements.

In [ ]:
#tensor1: This is the tensor you want to reshape.
#[3, 1]: This specifies the new shape of the tensor.

reshaped_tensor = tf.reshape(tensor1, [3, 1])
print(reshaped_tensor)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


#(4)tf.matmul () =>
-This TensorFlow function performs matrix multiplication between two tensors.

In [ ]:

tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])
matmul_result = tf.matmul(tensor_a, tensor_b)
print(matmul_result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


#(5)tf.transpose () =>
-tf.transpose() swaps the axes (dimensions) of a tensor, effectively flipping it along its axes.
- It's commonly used to change the shape of a matrix or higher-dimensional tensor, like converting rows into columns or vice versa

In [ ]:
print(tensor_a)
print("\n")
transposed_tensor = tf.transpose(tensor_a)
print(transposed_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


#(6)reduce_sum () =>
-tf.reduce_sum() calculates the sum of elements across a tensor's dimensions.
- You can sum over all elements or specify a particular axis (dimension) to reduce, making it useful for tasks like summing rows, columns, or the entire tensor.

In [ ]:
print(tensor_a)
print("\n")
sum_tensor = tf.reduce_sum(tensor_a)
print(sum_tensor)

NameError: name 'tensor_a' is not defined

#(7)reduce_mean() =>
-tf.reduce_mean() computes the average (mean) of elements across a tensor's dimensions.

- You can calculate the mean of all elements or specify an axis to reduce, which is helpful for averaging values across specific dimensions, like rows or columns, in a tensor

In [ ]:
print(tensor_a)
print("\n")
mean_tensor = tf.reduce_mean(tensor_a)
print(mean_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(2, shape=(), dtype=int32)


#(8)tf.reduce_max() =>
-computes the maximum value of elements in a tensor across specified dimensions.
- You can use it to find the maximum of all elements or along a particular axis, such as the highest value in a row or column of a tensor

In [ ]:
print(tensor_b)
print("\n")
max_tensor = tf.reduce_max(tensor_b)
print(max_tensor)

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(8, shape=(), dtype=int32)


#(9)tf.add() =>
-performs element-wise addition of two tensors. It adds corresponding elements from the two tensors, and the tensors must have the same shape (or be broadcastable).
- This function is useful for adding matrices, vectors, or scalars in TensorFlow operations.

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
added_tensors = tf.add(tensor_a, tensor_b)
print(added_tensors)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


#(10)tf.subtract() =>
-performs element-wise subtraction of two tensors in TensorFlow. It subtracts corresponding elements of the second tensor from the first tensor.
- Both tensors must have the same shape (or be broadcastable). This function is used for subtracting matrices, vectors, or scalars

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
subtracted_tensors = tf.subtract(tensor_a, tensor_b)
print(subtracted_tensors)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


#(11)tf.multiply() =>
-performs element-wise multiplication of two tensors. It multiplies corresponding elements from both tensors, and they must have the same shape (or be broadcastable).
- This function is commonly used for multiplying matrices, vectors, or scalars element by element in TensorFlow

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
multiplied_tensors = tf.multiply(tensor_a, tensor_b)
print(multiplied_tensors)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


#(12)tf.divide() ->
-performs element-wise division of two tensors in TensorFlow. It divides corresponding elements of the first tensor by the second tensor, and both tensors must have the same shape (or be broadcastable).
- This function is used for dividing matrices, vectors, or scalars element by element.

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
divided_tensors = tf.divide(tensor_a, tensor_b)
print(divided_tensors)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


#(13)slice () =>
-performing the slicing operation on tensor

In [ ]:
print(tensor_a)
print("\n")
sliced_tensor = tensor_a[:, 1]
print(sliced_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor([2 4], shape=(2,), dtype=int32)


#(14)tf.concat() =>
-combines two or more tensors along a specified axis. It takes a list of tensors and joins them into a single tensor, which is useful for merging data in machine learning tasks.
- The tensors must have compatible shapes except for the dimension being concatenated.

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
concat_tensor = tf.concat([tensor_a, tensor_b], axis=1)
print(concat_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)


#(15)tf.stack () =>
-TensorFlow function that combines multiple tensors (arrays) into a single tensor along a specified dimension.
- It helps create higher-dimensional data structures by stacking 1D or 2D tensors together, like adding layers in a stack.

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
stacked_tensor = tf.stack([tensor_a, tensor_b])
print(stacked_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


#(16)tf.split() =>
 -Tensorflow function that divides a tensor into multiple smaller tensors along a specified dimension. This is useful for breaking down larger datasets into manageable parts for processing or analysis

In [ ]:
print(tensor_a)
print("\n")
splitted_tensors = tf.split(tensor_a, num_or_size_splits=2, axis=1)
print(splitted_tensors)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


[<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]], dtype=int32)>, <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [4]], dtype=int32)>]


#(17)tf.expand_dims() =>
-TensorFlow function that adds an extra dimension to a tensor at a specified position.
- This is helpful for reshaping data, especially when you need to match the dimensions for operations like broadcasting or feeding into models

In [ ]:
print(tensor_a)
print("\n")
expanded_tensor = tf.expand_dims(tensor1, axis=0)
print(expanded_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


#(18)tf.squeeze() =>
-TensorFlow function that removes dimensions of size 1 from a tensor.
 - This is useful for simplifying the shape of a tensor, especially when you want to eliminate unnecessary dimensions after operations like tf.expand_dims()

In [ ]:
print(reshaped_tensor)
print("\n")
squeezed_tensor = tf.squeeze(reshaped_tensor)
print(squeezed_tensor)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


#(19) tf.tile() =>
-TensorFlow function that creates a new tensor by repeating an input tensor a specified number of times along each dimension.
- This is useful for expanding a tensor's shape or for creating larger datasets by replicating existing data in a structured way

In [ ]:
print(tensor1)
print("\n")
tiled_tensor = tf.tile(tensor1, [2])
print(tiled_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


tf.Tensor([1 2 3 1 2 3], shape=(6,), dtype=int32)


#(20)tf.one_hot() =>
-TensorFlow function that converts integer labels into a one-hot encoded format. In one-hot encoding, each label is represented as a vector where the index corresponding to the label is set to 1, and all other indices are set to 0.
- making it useful for categorical data in machine learning models.

In [ ]:
one_hot_tensor = tf.one_hot([0, 1, 2], depth=5)
print(one_hot_tensor)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


#(21)tf.eye() =>
-tf.eye() creates an identity matrix, which is a square matrix with ones on the diagonal and zeros elsewhere.
- It is often used in linear algebra for operations involving transformations and solving equations

In [ ]:
identity_matrix = tf.eye(5)
print(identity_matrix)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


#(22)tf.zeros() =>
-tensor (an n-dimensional array) filled with zeros.
- It is useful for initializing weights in machine learning models or for creating placeholders in computations

In [ ]:
zeros_matrix = tf.zeros([2, 3])
print(zeros_matrix)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


#(23) tf.ones () =>
-tensor filled with ones. It is commonly used to initialize weights or to create masks in computations where a value of one is needed for specific operations.


In [ ]:
ones_matrix = tf.ones([3, 2])
print(ones_matrix)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#(24)tf.fill() =>
-creates a tensor of a specified shape, filled with a specified value. It is useful for initializing tensors with custom values for various applications in computations and machine learning.

In [ ]:
filled_tensor = tf.fill([2, 3], value=5)
print(filled_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


#(25)tf.cast () =>
-tensor from one data type to another. This is useful when you need to ensure that the tensor's type is compatible with certain operations, such as converting integers to floats for mathematical calculations.

In [ ]:
casted_tensor = tf.cast(tensor1, dtype=tf.float32)
print(casted_tensor )

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


#(26) tf.nn.relu() =>
-Changes all negative numbers to zero and keeps positive numbers unchanged.
- It’s commonly used in neural networks to introduce non-linearity, helping the model learn complex patterns

In [ ]:
print(tensor_a)
print("\n")
relu_tensor = tf.nn.relu(tensor_a)
print(relu_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#(27)tf.square() =>
 -Squares each value in the tensor (multiplies each by itself).
 - This is often used to emphasize larger numbers or in mathematical computations like finding distance.

In [ ]:
print(tensor_a)
print("\n")
square_tensor = tf.square(tensor_a)
print(square_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


#(28)tf.sqrt() =>
 -Finds the square root of each element in the tensor.
 - It's used to reverse a squaring operation or in geometry when working with distances.

In [ ]:
print(tensor_b)
print("\n")
sqrt_tensor = tf.sqrt(tf.cast(tensor_b, dtype=tf.float32))
print(sqrt_tensor)

NameError: name 'tensor_b' is not defined

#(29)tf.tensordot() =>
-Performs a dot product on two tensors, combining them along specified axes.
- This is used in linear algebra to compute products like between vectors or matrices.

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
dot_product = tf.tensordot(tensor_a, tensor_b, axes=1)
print(dot_product)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


#(30)tf.linalg.matmul() =>
 -Multiplies two matrices together.
 - It’s used in many computations, especially in neural networks, where matrix operations are crucial for data transformatio

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
batched_matmul = tf.linalg.matmul([tensor_a], [tensor_b])
print(batched_matmul)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[[19 22]
  [43 50]]], shape=(1, 2, 2), dtype=int32)


#(31)tf.argmax() =>
-Finds the index of the largest value in a tensor along a specified axis.
- It’s commonly used to get the predicted class in classification tasks.

In [ ]:
print(tensor_b)
print("\n")
argmax_tensor = tf.argmax(tensor_b, axis=1)
print(argmax_tensor)

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor([1 1], shape=(2,), dtype=int64)


#(32)tf.argmin() =>
-Finds the index of the smallest value in a tensor along a specified axis.
- It helps locate the minimum value's position within the data.

In [ ]:
print(tensor_a)
print("\n")
argmin_tensor = tf.argmin(tensor_a, axis=0)
print(argmin_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor([0 0], shape=(2,), dtype=int64)


#(33)tf.abs() =>
-Returns the absolute value of each element in a tensor, removing any negative signs.
- It’s useful when you want to work with the magnitude of numbers, regardless of their sign.

In [ ]:
absolute_tensor = tf.abs(tf.constant([-1, -2, 3]))
print(absolute_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


#(34)tf.keras.losses.cosine_similarity()=>
 -Measures the cosine similarity between two vectors, where 1 means they are perfectly aligned and -1 means they are in opposite directions.
 - It’s used to compare how similar two things are in direction, ignoring magnitude.

In [ ]:
print(tensor_a)
print("\n")
print(tensor_b)
print("\n")
cosine_similarity = tf.keras.losses.cosine_similarity(tensor_a, tensor_b)
print(cosine_similarity)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


tf.Tensor([-0.97341716 -0.99716413], shape=(2,), dtype=float32)


#Data set

In [ ]:
y_true = tf.constant([1.0, 2.0, 3.0])
y_pred = tf.constant([1.5, 2.5, 3.5])

#(35)tf.keras.losses.hinge() =>
 -A loss function used for classification tasks, especially in Support Vector Machines (SVMs).
 - It calculates the hinge loss, which penalizes incorrect classifications and encourages a margin between different classes

In [ ]:
print(y_true)
print("\n")
print(y_pred)
print("\n")
hinge_loss = tf.keras.losses.hinge(y_true, y_pred)
print(hinge_loss)


tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)


tf.Tensor(0.0, shape=(), dtype=float32)
